# ------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright © 2024 The Protobom Authors
# SPDX-FileType: SOURCE
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------
# This workflow uses actions that are not certified by
# GitHub. They are provided by a third-party and are
# governed by separate terms of service, privacy policy,
# and support documentation.
# ------------------------------------------------------------------------
---
name: golangci-lint

on:
  pull_request:
    branches: main
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: go.mod
          cache: false
          check-latest: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@82d40c283aeb1f2b6595839195e95c2d6a49081b # v5.0.0
        with:
          version: v1.59
