# ------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright © 2024 The Protobom Authors
# SPDX-FileType: SOURCE
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------
# This workflow uses actions that are not certified by
# GitHub. They are provided by a third-party and are
# governed by separate terms of service, privacy policy,
# and support documentation.
# ------------------------------------------------------------------------
---
name: test

on:
  pull_request:
    branches: main
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod
          cache: false
          check-latest: true

      - name: Run tests
        run: make test-unit
